# Generated by Django 5.2.12 on 2026-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='django-meeting', max_length=100, verbose_name='Nom du site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Couleur primaire')),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7, verbose_name='Couleur secondaire')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='Serveur SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Port SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='TLS activé')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='Identifiant SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='Mot de passe SMTP')),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254, verbose_name='Email expéditeur')),
                ('retention_days', models.PositiveIntegerField(default=90, help_text='Nombre de jours avant suppression automatique après clôture', verbose_name='Rétention (jours)')),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
    ]
